# Generated by Django 5.1 on 2024-09-24 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_email_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='accountant_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='geo_location',
            field=models.CharField(blank=True, help_text='Format: latitude,longitude', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(default='', upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='school',
            name='mentor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='principal_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='teacher_coordinator',
            field=models.CharField(blank=True, help_text='Enter multiple coordinators separated by commas.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='grades',
            field=models.CharField(blank=True, choices=[('grade_1', 'Grade 1'), ('grade_2', 'Grade 2'), ('grade_3', 'Grade 3'), ('grade_4', 'Grade 4'), ('grade_5', 'Grade 5'), ('grade_6', 'Grade 6'), ('grade_7', 'Grade 7'), ('grade_8', 'Grade 8'), ('grade_9', 'Grade 9'), ('grade_10', 'Grade 10'), ('grade_11', 'Grade 11'), ('grade_12', 'Grade 12')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='mobile_num',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('school', 'school'), ('student', 'student'), ('teacher', 'teacher')], max_length=10),
        ),
    ]
