# Generated by Django 5.1 on 2024-09-25 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_role_macroplanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('school', 'school'), ('teacher', 'teacher')], max_length=10),
        ),
        migrations.CreateModel(
            name='Microplanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(default='', max_length=100)),
                ('school', models.CharField(choices=[('Sparsh Global SChool,Greater Noida', 'Sparsh Global SChool,Greater Noida'), ('JP International School,Greater Noida', 'JP International School,Greater Noida'), ('SPS,Sonipat', 'SPS,Sonipat'), ('Vivekanand School,Delhi', 'Vivekanand School,Delhi'), ('Blooming Dale School,Budaun', 'Blooming Dale School,Budaun'), ('Satya Prakash Public School, Jabalpur', 'Satya Prakash Public School, Jabalpur')], max_length=100)),
                ('microplanner', models.FileField(upload_to='microplanner/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
