# Generated by Django 5.1 on 2024-09-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_advocacyvisit_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('school', 'school'), ('teacher', 'teacher')], max_length=10),
        ),
    ]
