# Generated by Django 5.1 on 2024-09-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_curriculumview_guestsession_kreativityshow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('school', 'school'), ('student', 'student'), ('teacher', 'teacher')], max_length=10),
        ),
    ]
