# Generated by Django 5.1 on 2024-09-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('school', 'school'), ('teacher', 'teacher'), ('student', 'student')], max_length=10),
        ),
    ]
