# Generated by Django 5.1 on 2024-09-30 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='mentor',
        ),
        migrations.AddField(
            model_name='school',
            name='account_email',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='account_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='principal_email',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='principal_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='school',
            name='teacher_coordinator_email',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='teacher_coordinator_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('teacher', 'teacher'), ('school', 'school'), ('student', 'student')], max_length=10),
        ),
    ]
