# Generated by Django 5.1 on 2024-09-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_school_mentor_school_account_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student'), ('school', 'school')], max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(default='', null=True, upload_to='logo/'),
        ),
    ]
