# Generated by Django 5.1 on 2024-09-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_customuser_role_alter_school_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='logo',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher'), ('school', 'school')], max_length=10),
        ),
    ]
