# Generated by Django 5.1 on 2024-09-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_school_logo_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('school', 'school'), ('student', 'student'), ('teacher', 'teacher')], max_length=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='account_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='principal_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacher_coordinator_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='teacher_coordinator_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
