# Generated by Django 5.1 on 2024-10-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_customuser_role_alter_school_account_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('teacher', 'teacher'), ('school', 'school'), ('student', 'student')], max_length=10),
        ),
    ]
