# Generated by Django 5.1 on 2024-10-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('teacher', 'teacher'), ('school', 'school')], max_length=10),
        ),
    ]
