# Generated by Django 5.1 on 2024-10-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_customuser_role_notificationstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='student_profile_pic/', verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('school', 'school'), ('teacher', 'teacher'), ('student', 'student')], max_length=10),
        ),
    ]
