# Generated by Django 5.1 on 2024-10-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_student_profile_pic_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student'), ('school', 'school')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='Images/student_profile_pic/', verbose_name='Profile Image'),
        ),
    ]
