# Generated by Django 5.1 on 2024-10-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_student_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('school', 'school'), ('student', 'student'), ('teacher', 'teacher')], max_length=10),
        ),
    ]
