# Generated by Django 5.1 on 2024-09-26 06:18

import autoslug.fields
import curriculum.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanzo_kit_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_id', models.CharField(max_length=50)),
                ('kit_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from=models.CharField(max_length=255, unique=True), unique=True)),
            ],
            options={
                'verbose_name_plural': '1. Schools',
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from=models.CharField(max_length=100, unique=True), unique=True)),
            ],
            options={
                'verbose_name_plural': '1. Standard',
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to=curriculum.models.save_subject_image, verbose_name='Subject Image')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('display_on_frontend', models.BooleanField(default=True, verbose_name='Display on Frontend')),
                ('level', models.CharField(blank=True, choices=[('Phase-I', 'Phase I'), ('Phase-II', 'Phase II'), ('Phase-III', 'Phase III')], max_length=10, null=True, verbose_name='Level')),
            ],
            options={
                'verbose_name_plural': '2. Teacher Subjects',
            },
        ),
        migrations.CreateModel(
            name='Mechanzo_model_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('file', models.FileField(blank=True, upload_to=curriculum.models.save_mechanzo_file, verbose_name='Mechanzo')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mechanzo_models', to='curriculum.mechanzo_kit_name')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to=curriculum.models.save_subject_image, verbose_name='Subject Image')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('display_on_frontend', models.BooleanField(default=True, verbose_name='Display on Frontend')),
                ('schools', models.ManyToManyField(to='curriculum.school')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='curriculum.standard')),
            ],
            options={
                'verbose_name_plural': '2. Subjects',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('position', models.PositiveSmallIntegerField(verbose_name='Chapter no.')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('video', models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Videos')),
                ('prerequisite', models.FileField(blank=True, upload_to=curriculum.models.save_lesson_files, verbose_name='Presentations')),
                ('assessment', models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Assessment')),
                ('notes', models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Learning Aids')),
                ('editor', models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Editor')),
                ('display_on_frontend', models.BooleanField(default=True, verbose_name='Display on Frontend')),
                ('schools', models.ManyToManyField(to='curriculum.school')),
                ('Standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.standard')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.subject')),
            ],
            options={
                'verbose_name_plural': '3. Lessons',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='TeacherLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250)),
                ('position', models.PositiveSmallIntegerField(verbose_name='Chapter no.')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('video', models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Videos')),
                ('assessment', models.URLField(blank=True, default='', max_length=300, null=True, verbose_name='Assessment')),
                ('display_on_frontend', models.BooleanField(default=True, verbose_name='Display on Frontend')),
                ('module', models.CharField(blank=True, choices=[('Module 1', 'Module 1'), ('Module 2', 'Module 2'), ('Module 3', 'Module 3')], max_length=10, null=True, verbose_name='Module')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teacher_lessons', to='curriculum.teachersubject')),
            ],
            options={
                'verbose_name_plural': '3. Teacher Lessons',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='LectureRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=0)),
                ('date_rated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.lesson')),
            ],
            options={
                'unique_together': {('lecture', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='curriculum.teacherlesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '4. User Lesson Progress',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
