# Generated by Django 5.1 on 2024-09-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
