# Generated by Django 5.1 on 2024-12-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_alter_lessonaccessreport_video_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonaccessreport',
            name='content_time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonaccessreport',
            name='hint_time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
