# Generated by Django 5.1 on 2024-12-12 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_alter_lessonaccessreport_content_time_spent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonAccessReport',
        ),
    ]
